### ISSUE TITLE
ミニカーサポートの作成について

### ISSUE THREAD

**Issue by YatsuT** [FaBoPlatform/AutowareDocs#1]
AutowareDocsを拝見しました。
現在、自身の所属する部署の取り組みとして、まさに記事で行われていたような自動運転ソフトを搭載したミニカーの
走る実験環境を作成したいと考えているのですが、
ハードウェアの組み立て等に明るくないこともあり、作成にあたって助力を乞いたいと思い、無理を承知で連絡させていただきました。

もしもご興味を持って頂けるようでしたら詳細や謝礼のお話もいたしたく、連絡手段をご教示頂ければ幸いです。

**Comment by naisy** [comment]
@YatsuT 
秘匿する情報はないですので、FaBoのdiscordにあるautowareチャンネルでお気軽に聞いていただければと思います。
FaBoのdiscordには、自動走行に興味のある一般の方が多く参加されていますので、個人情報や機密情報がありましたら、記載されないように注意していただければと思います。
FaBo discord：https://discord.gg/VUQybhs
